name: kayaknet
version: '1.0.0'
summary: Anonymous Encrypted Network
description: |
  KayakNet is a decentralized anonymous network for private communication
  and commerce. Features include:
  - End-to-end encrypted messaging
  - Anonymous marketplace with crypto escrow
  - .kyk domain registration
  - Onion routing for traffic analysis resistance
  
  No servers. No logs. No compromise.

grade: stable
confinement: strict
base: core22

architectures:
  - build-on: amd64

apps:
  kayaknet:
    command: bin/kayaknet-gui
    desktop: share/applications/kayaknet.desktop
    extensions: [gnome]
    plugs:
      - home
      - network
      - network-bind
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - unity7

parts:
  kayaknet:
    plugin: python
    source: .
    python-packages:
      - PyGObject
    stage-packages:
      - python3-gi
      - python3-gi-cairo
      - gir1.2-gtk-3.0
      - libgtk-3-0
    override-build: |
      craftctl default
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp kayaknet-gui.py $SNAPCRAFT_PART_INSTALL/bin/kayaknet-gui
      chmod +x $SNAPCRAFT_PART_INSTALL/bin/kayaknet-gui
      
      mkdir -p $SNAPCRAFT_PART_INSTALL/share/applications
      cat > $SNAPCRAFT_PART_INSTALL/share/applications/kayaknet.desktop << EOF
      [Desktop Entry]
      Name=KayakNet
      Comment=Anonymous Encrypted Network
      Exec=kayaknet-gui
      Icon=\${SNAP}/share/icons/kayaknet.png
      Terminal=false
      Type=Application
      Categories=Network;Security;
      EOF
      
      mkdir -p $SNAPCRAFT_PART_INSTALL/share/icons
      # Icon will be added during build

